### ISSUE TITLE
Automatic launc

### ISSUE THREAD

**Issue by msancg** [odoo/ps-runbot-testing#2]
Good morning,
I am glad I found this tool as it looks what I was looking for to test and trace errors on ODOO custom developments.
I have 2 questions regarding the tool:
- Is it possible to porgramatically automate the execution on the test, without depending on a person clicking the "Run" button? Or some way to run all existing tests at once?
- Does the tool keep the log of executions whether they were sucessful or failed?
- Is there any way in which we can set ODOO or email notifications if one of the tests failed?
- Is this module compatible with ODOO 14.0?
Thanks in advance and regards,
María.

**Comment by sts-odoo** [comment]
> Good morning,
> I am glad I found this tool as it looks what I was looking for to test and trace errors on ODOO custom developments.
> I have 2 questions regarding the tool:
> 
> * Is it possible to porgramatically automate the execution on the test, without depending on a person clicking the "Run" button? Or some way to run all existing tests at once?
> * Does the tool keep the log of executions whether they were sucessful or failed?
> * Is there any way in which we can set ODOO or email notifications if one of the tests failed?
> * Is this module compatible with ODOO 14.0?
Haven't tried but version 13.0 might be 
>   Thanks in advance and regards,
>   María.

The purpose of this module is to record action to create the tests, not actually run them.
